package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CARD_NUM.
 */
public class CardNum {

    private Long id;
    private String card_sn;

    public CardNum() {
    }

    public CardNum(Long id) {
        this.id = id;
    }

    public CardNum(Long id, String card_sn) {
        this.id = id;
        this.card_sn = card_sn;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCard_sn() {
        return card_sn;
    }

    public void setCard_sn(String card_sn) {
        this.card_sn = card_sn;
    }

}
