package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SCHOOLS_USER.
 */
public class SchoolsUser {

    private Long id;
    private String no_pass_add_time;
    private String daily_use_amount;
    private String daily_use_num;
    private String is_bind_parents;
    private String new_card_type;
    private String card_sn;
    private String token;
    private String openid;
    private String agent_token;
    private String agent_openid;
    private String user_type;
    private String group_id;
    private String user_level;
    private String group_id_admin;
    private String name;
    private String sex;
    private String birthday;
    private String phone;
    private String verify_code;
    private String is_verified;
    private String verify_time;
    private String account_deposit;
    private String subject;
    private String is_subscribe;
    private String subscribe_openid;
    private String origin_card_sn;
    private String unionId;
    private String app_openid;

    public SchoolsUser() {
    }

    public SchoolsUser(Long id) {
        this.id = id;
    }

    public SchoolsUser(Long id, String no_pass_add_time, String daily_use_amount, String daily_use_num, String is_bind_parents, String new_card_type, String card_sn, String token, String openid, String agent_token, String agent_openid, String user_type, String group_id, String user_level, String group_id_admin, String name, String sex, String birthday, String phone, String verify_code, String is_verified, String verify_time, String account_deposit, String subject, String is_subscribe, String subscribe_openid, String origin_card_sn, String unionId, String app_openid) {
        this.id = id;
        this.no_pass_add_time = no_pass_add_time;
        this.daily_use_amount = daily_use_amount;
        this.daily_use_num = daily_use_num;
        this.is_bind_parents = is_bind_parents;
        this.new_card_type = new_card_type;
        this.card_sn = card_sn;
        this.token = token;
        this.openid = openid;
        this.agent_token = agent_token;
        this.agent_openid = agent_openid;
        this.user_type = user_type;
        this.group_id = group_id;
        this.user_level = user_level;
        this.group_id_admin = group_id_admin;
        this.name = name;
        this.sex = sex;
        this.birthday = birthday;
        this.phone = phone;
        this.verify_code = verify_code;
        this.is_verified = is_verified;
        this.verify_time = verify_time;
        this.account_deposit = account_deposit;
        this.subject = subject;
        this.is_subscribe = is_subscribe;
        this.subscribe_openid = subscribe_openid;
        this.origin_card_sn = origin_card_sn;
        this.unionId = unionId;
        this.app_openid = app_openid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNo_pass_add_time() {
        return no_pass_add_time;
    }

    public void setNo_pass_add_time(String no_pass_add_time) {
        this.no_pass_add_time = no_pass_add_time;
    }

    public String getDaily_use_amount() {
        return daily_use_amount;
    }

    public void setDaily_use_amount(String daily_use_amount) {
        this.daily_use_amount = daily_use_amount;
    }

    public String getDaily_use_num() {
        return daily_use_num;
    }

    public void setDaily_use_num(String daily_use_num) {
        this.daily_use_num = daily_use_num;
    }

    public String getIs_bind_parents() {
        return is_bind_parents;
    }

    public void setIs_bind_parents(String is_bind_parents) {
        this.is_bind_parents = is_bind_parents;
    }

    public String getNew_card_type() {
        return new_card_type;
    }

    public void setNew_card_type(String new_card_type) {
        this.new_card_type = new_card_type;
    }

    public String getCard_sn() {
        return card_sn;
    }

    public void setCard_sn(String card_sn) {
        this.card_sn = card_sn;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getOpenid() {
        return openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public String getAgent_token() {
        return agent_token;
    }

    public void setAgent_token(String agent_token) {
        this.agent_token = agent_token;
    }

    public String getAgent_openid() {
        return agent_openid;
    }

    public void setAgent_openid(String agent_openid) {
        this.agent_openid = agent_openid;
    }

    public String getUser_type() {
        return user_type;
    }

    public void setUser_type(String user_type) {
        this.user_type = user_type;
    }

    public String getGroup_id() {
        return group_id;
    }

    public void setGroup_id(String group_id) {
        this.group_id = group_id;
    }

    public String getUser_level() {
        return user_level;
    }

    public void setUser_level(String user_level) {
        this.user_level = user_level;
    }

    public String getGroup_id_admin() {
        return group_id_admin;
    }

    public void setGroup_id_admin(String group_id_admin) {
        this.group_id_admin = group_id_admin;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getVerify_code() {
        return verify_code;
    }

    public void setVerify_code(String verify_code) {
        this.verify_code = verify_code;
    }

    public String getIs_verified() {
        return is_verified;
    }

    public void setIs_verified(String is_verified) {
        this.is_verified = is_verified;
    }

    public String getVerify_time() {
        return verify_time;
    }

    public void setVerify_time(String verify_time) {
        this.verify_time = verify_time;
    }

    public String getAccount_deposit() {
        return account_deposit;
    }

    public void setAccount_deposit(String account_deposit) {
        this.account_deposit = account_deposit;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getIs_subscribe() {
        return is_subscribe;
    }

    public void setIs_subscribe(String is_subscribe) {
        this.is_subscribe = is_subscribe;
    }

    public String getSubscribe_openid() {
        return subscribe_openid;
    }

    public void setSubscribe_openid(String subscribe_openid) {
        this.subscribe_openid = subscribe_openid;
    }

    public String getOrigin_card_sn() {
        return origin_card_sn;
    }

    public void setOrigin_card_sn(String origin_card_sn) {
        this.origin_card_sn = origin_card_sn;
    }

    public String getUnionId() {
        return unionId;
    }

    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    public String getApp_openid() {
        return app_openid;
    }

    public void setApp_openid(String app_openid) {
        this.app_openid = app_openid;
    }

}
