package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SCHOOLS.
 */
public class Schools {

    private Long id;
    private String token;
    private String room_id;
    private String desc;

    public Schools() {
    }

    public Schools(Long id) {
        this.id = id;
    }

    public Schools(Long id, String token, String room_id, String desc) {
        this.id = id;
        this.token = token;
        this.room_id = room_id;
        this.desc = desc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getRoom_id() {
        return room_id;
    }

    public void setRoom_id(String room_id) {
        this.room_id = room_id;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

}
