package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Users.
 */
public class Users {

    private Long id;
    private String order_id;
    private String goods_name;
    private String goods_num;
    private String user_name;
    private String user_id;
    private String user_phone;
    private String valid_start;
    private String valid_end;
    private Boolean is_receive;
    private String group_name;
    private String user_type;
    private String dish_date;

    public Users() {
    }

    public Users(Long id) {
        this.id = id;
    }

    public Users(Long id, String order_id, String goods_name, String goods_num, String user_name, String user_id, String user_phone, String valid_start, String valid_end, Boolean is_receive, String group_name, String user_type, String dish_date) {
        this.id = id;
        this.order_id = order_id;
        this.goods_name = goods_name;
        this.goods_num = goods_num;
        this.user_name = user_name;
        this.user_id = user_id;
        this.user_phone = user_phone;
        this.valid_start = valid_start;
        this.valid_end = valid_end;
        this.is_receive = is_receive;
        this.group_name = group_name;
        this.user_type = user_type;
        this.dish_date = dish_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrder_id() {
        return order_id;
    }

    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }

    public String getGoods_name() {
        return goods_name;
    }

    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name;
    }

    public String getGoods_num() {
        return goods_num;
    }

    public void setGoods_num(String goods_num) {
        this.goods_num = goods_num;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_phone() {
        return user_phone;
    }

    public void setUser_phone(String user_phone) {
        this.user_phone = user_phone;
    }

    public String getValid_start() {
        return valid_start;
    }

    public void setValid_start(String valid_start) {
        this.valid_start = valid_start;
    }

    public String getValid_end() {
        return valid_end;
    }

    public void setValid_end(String valid_end) {
        this.valid_end = valid_end;
    }

    public Boolean getIs_receive() {
        return is_receive;
    }

    public void setIs_receive(Boolean is_receive) {
        this.is_receive = is_receive;
    }

    public String getGroup_name() {
        return group_name;
    }

    public void setGroup_name(String group_name) {
        this.group_name = group_name;
    }

    public String getUser_type() {
        return user_type;
    }

    public void setUser_type(String user_type) {
        this.user_type = user_type;
    }

    public String getDish_date() {
        return dish_date;
    }

    public void setDish_date(String dish_date) {
        this.dish_date = dish_date;
    }

}
