package com.saineng.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Users;
import greendao.Orders;
import greendao.FoodBean;
import greendao.CardNum;
import greendao.Schools;

import com.saineng.dao.UsersDao;
import com.saineng.dao.OrdersDao;
import com.saineng.dao.FoodBeanDao;
import com.saineng.dao.CardNumDao;
import com.saineng.dao.SchoolsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usersDaoConfig;
    private final DaoConfig ordersDaoConfig;
    private final DaoConfig foodBeanDaoConfig;
    private final DaoConfig cardNumDaoConfig;
    private final DaoConfig schoolsDaoConfig;

    private final UsersDao usersDao;
    private final OrdersDao ordersDao;
    private final FoodBeanDao foodBeanDao;
    private final CardNumDao cardNumDao;
    private final SchoolsDao schoolsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        ordersDaoConfig = daoConfigMap.get(OrdersDao.class).clone();
        ordersDaoConfig.initIdentityScope(type);

        foodBeanDaoConfig = daoConfigMap.get(FoodBeanDao.class).clone();
        foodBeanDaoConfig.initIdentityScope(type);

        cardNumDaoConfig = daoConfigMap.get(CardNumDao.class).clone();
        cardNumDaoConfig.initIdentityScope(type);

        schoolsDaoConfig = daoConfigMap.get(SchoolsDao.class).clone();
        schoolsDaoConfig.initIdentityScope(type);

        usersDao = new UsersDao(usersDaoConfig, this);
        ordersDao = new OrdersDao(ordersDaoConfig, this);
        foodBeanDao = new FoodBeanDao(foodBeanDaoConfig, this);
        cardNumDao = new CardNumDao(cardNumDaoConfig, this);
        schoolsDao = new SchoolsDao(schoolsDaoConfig, this);

        registerDao(Users.class, usersDao);
        registerDao(Orders.class, ordersDao);
        registerDao(FoodBean.class, foodBeanDao);
        registerDao(CardNum.class, cardNumDao);
        registerDao(Schools.class, schoolsDao);
    }
    
    public void clear() {
        usersDaoConfig.getIdentityScope().clear();
        ordersDaoConfig.getIdentityScope().clear();
        foodBeanDaoConfig.getIdentityScope().clear();
        cardNumDaoConfig.getIdentityScope().clear();
        schoolsDaoConfig.getIdentityScope().clear();
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

    public OrdersDao getOrdersDao() {
        return ordersDao;
    }

    public FoodBeanDao getFoodBeanDao() {
        return foodBeanDao;
    }

    public CardNumDao getCardNumDao() {
        return cardNumDao;
    }

    public SchoolsDao getSchoolsDao() {
        return schoolsDao;
    }

}
